name: Build macOS App

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install py2app
        pip install pillow
        pip install openpyxl
    
    - name: Create setup.py
      run: |
        echo 'from setuptools import setup
        setup(
            app=["main.py"],
            setup_requires=["py2app"],
            options={
                "py2app": {
                    "argv_emulation": True,
                    "packages": ["PIL", "openpyxl", "tkinter"],
                    "includes": ["tkinter"]
                }
            }
        )' > setup.py
    
    - name: Build app
      run: |
        python setup.py py2app
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: SecretSanta
        path: dist/*.app
